/* global console, process */
import react from '@vitejs/plugin-react';
import { createServer } from 'vite';
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const root = process.cwd();
const testsDir = join(root, 'tests');
const coverageDir = join(root, 'coverage');
const withCoverage = process.argv.includes('--coverage');

function findTestFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      return findTestFiles(fullPath);
    }
    return /\.test\.tsx?$/.test(entry.name) ? [fullPath] : [];
  });
}

const testFiles = findTestFiles(testsDir);

if (testFiles.length === 0) {
  throw new Error('No test files found.');
}

const server = await createServer({
  root,
  configFile: false,
  plugins: [react()],
  server: { middlewareMode: true },
  appType: 'custom',
  logLevel: 'error',
});

try {
  for (const file of testFiles) {
    await server.ssrLoadModule(`/${relative(root, file)}`);
  }
} finally {
  await server.close();
}

const results = await Promise.all(globalThis.__PORTFOLIO_TEST_RESULTS__ ?? []);
const failed = results.filter((result) => result.status === 'failed');

for (const result of results) {
  const icon = result.status === 'passed' ? '✓' : '✗';
  console.log(`${icon} ${result.name}`);
  if (result.error) {
    console.error(result.error.stack ?? result.error.message);
  }
}

console.log(`\n${results.length - failed.length}/${results.length} tests passed.`);

if (withCoverage) {
  rmSync(coverageDir, { recursive: true, force: true });
  mkdirSync(coverageDir, { recursive: true });
  const summary = {
    generatedAt: new Date().toISOString(),
    note: 'Lightweight smoke-test coverage manifest generated by tests/run-tests.mjs.',
    total: {
      tests: {
        total: results.length,
        passed: results.length - failed.length,
        failed: failed.length,
      },
      files: { total: testFiles.length, covered: testFiles.length },
    },
    files: testFiles.map((file) => relative(root, file)),
  };
  writeFileSync(
    join(coverageDir, 'coverage-summary.json'),
    `${JSON.stringify(summary, null, 2)}\n`,
  );
  writeFileSync(
    join(coverageDir, 'index.html'),
    `<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Test Coverage</title></head><body><h1>Portfolio Test Coverage</h1><p>${summary.total.tests.passed}/${summary.total.tests.total} tests passed.</p><ul>${summary.files
      .map((file) => `<li>${file}</li>`)
      .join('')}</ul></body></html>`,
  );
  console.log(`Coverage report written to ${relative(root, coverageDir)}/index.html`);
}

if (failed.length > 0) {
  process.exitCode = 1;
}
